name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags like v1.0, v1.2.3, etc.
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --noconsole --name EligibilityGenerator main.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: D:/a/Eligibility-Report-Creator/Eligibility-Report-Creator/dist/EligibilityGenerator.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
